#!/bin/bash
#PBS -q normal
#PBS -l nodes=2:ppn=32
#PBS -l walltime=1:00:00
#PBS -N bundler.trestles
. /etc/profile.d/modules.sh

TASKS=tasks         # the name of your tasks list
module load octave  # if your tasks need the octave module 

cd $PBS_O_WORKDIR
module load intel   # necessary for bundler.py on Trestles
mpirun_rsh \
           -np $(cat $TASKS | wc -l) \
           -hostfile $PBS_NODEFILE \
           MV2_ENABLE_AFFINITY=0 \
           ./bundler.py $TASKS
